spring.application.name=template
server.port=8080

# Datasource(MySQL)
spring.datasource.url=your_db_url
spring.datasource.username=
spring.datasource.password=

# JPA (dev mode)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Jackson
spring.jackson.mapper.accept-case-insensitive-enums=true

# CORS
app.cors.allowed-origin=http://localhost:5173

# JWT
# JWT? ??? ???? ???????.
security.jwt.secret-key=${JWT_SECRET:ZKOiUFNIL8huvgm2/dleFikkvaD4WCChcRIpc3NkJaLtuGDA8ETfWuPcayJwOCxMlL/+joNWc4b4LKB3IHaAMQ==}
security.jwt.access-expiration=${JWT_ACCESS_EXPIRATION:1800}
security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:1209600}

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
